/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jhl_audiolibrary_utils_FFTUtil */

#ifndef _Included_com_jhl_audiolibrary_utils_FFTUtil
#define _Included_com_jhl_audiolibrary_utils_FFTUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jhl_audiolibrary_utils_FFTUtil
 * Method:    processSampleData
 * Signature: ([BI)D
 */
JNIEXPORT jdouble JNICALL Java_com_jhl_audiolibrary_utils_FFTUtil_processSampleData
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
